### ISSUE TITLE
Neptunia VII crashes with neptasm

### ISSUE THREAD

**Issue by ghost** [tlaik/neptasm#1]
After extracting dinput8.dll into game's base directory neptunia will instantly crash after creating window.
Console output doesn't contain anything useful (or anything at all).
Changing the settings in the ini file does not change anything, it will continue crashing.
Without dinput8.dll game works just fine.

Info:
Windows 11 Pro
GPU drivers: Radeon Pro 23.7.2
Steam version of neptunia vii

**Comment by tlaik** [comment]
Any chance you can try it out on Win 10?
I don't have 11 myself, would be nice to rule it out as possible cause.

**Comment by ghost** [comment]
Sorry for late response
> Any chance you can try it out on Win 10?

Yeah sure, i will check it on both linux with dxvk and win10 when i will have time for that

**Comment by ghost** [comment]
Closing this because i don't have this issue anymore.
